services:
  - type: web
    name: raiz-pixel-api
    runtime: docker
    dockerfilePath: ./sistema/Dockerfile
    buildContext: .
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_DRIVER
        value: pgsql
